name: Build and Upload Exe

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run installResources.ps1
      shell: powershell
      run: .\installResources.ps1

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Build exe files
      run: |
        pyinstaller --onefile /lab678/components.py
        pyinstaller --onefile /lab678/pars.py
        pyinstaller --onefile /lab678/json_składnia.py
        pyinstaller --onefile /lab678/json_zgodność.py
        pyinstaller --onefile /lab678/yaml_weryfikacja.py
        pyinstaller --onefile /lab678/yaml_zgodność.py
        pyinstaller --onefile /lab678/xml_weryfikacja.py
        pyinstaller --onefile /lab678/xml_zgodność.py

    - name: Upload exe files
      uses: actions/upload-artifact@v3
      with:
        name: exe-files
        path: |
          components/dist/components.exe
          pars/dist/pars.exe
          json_składnia/dist/json_składnia.exe
          json_zgodność/dist/json_zgodność.exe
          yaml_weryfikacja/dist/yaml_weryfikacja.exe
          yaml_zgodność/dist/yaml_zgodność.exe
          xml_weryfikacja/dist/xml_weryfikacja.exe
          xml_zgodność/dist/xml_zgodność.exe
